spring:
  application:
    name: slack-service
  datasource:
    url: jdbc:postgresql://localhost:5432/b2b
    username: postgres
    password: qwer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true

server:
  port: 19096
  swagger:
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

slack:
  token: ${SLACK_TOKEN}
  id: ${SLACK_CHANNEL_ID}

weather:
  api:
    url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    serviceKey: ${WEATHER_SERVICE_KEY}

gemini:
  api:
    url: https://generativelanguage.googleapis.com
    key: ${GEMINI_KEY}

springdoc:
  api-docs:
    path: /api/slack-messages/v3/api-docs
  swagger-ui:
    path: /api/slack-messages/swagger-ui.html
