server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
      discovery:
        locator:
          enabled: true
  security:
    csrf:
      enabled: false  # CSRF 비활성화

jwt:
  audience: b2b-client
  expiration-minutes: 30
  secret-key: local-three-iii-authenticate-secret-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
