server:
  port: 19091  # ????? ???? ??? ?? ??

spring:
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  application:
    name: gateway-service  # ?????? ??? 'gateway-service'? ??
  cloud:
    gateway:
      routes:  # Spring Cloud Gateway? ??? ??
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: service
          uri: lb://service
          predicates:
            - Path=/api/**
      discovery:
        locator:
          enabled: true  # ??? ?????? ?? ???? ???? ????? ??

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ??? URL? ??