spring:
  application:
    name: user-service  # 서비스 등록
  datasource:
    url: jdbc:postgresql://localhost:5432/b2b
    username: postgres
    password: qwer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true

jwt:
  audience: b2b-client
  expiration-minutes: 30
  secret-key: local-three-iii-authenticate-secret-key

server:
  port: 19092
  swagger:
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

springdoc:
  api-docs:
    path: /api/auth/v3/api-docs
  swagger-ui:
    path: /api/auth/swagger-ui.html

gateway:
  url: localhost:19091
